version: "2"
services:
  varnish:
    image: meanbee/magento2-varnish:latest
    hostname: ${PROJECT_HOSTNAME}
    ports:
      - 80
    environment:
      VIRTUAL_HOST: ${PROJECT_HOSTNAME}
      VIRTUAL_PORT: 80
      HTTPS_METHOD: noredirect
      CERT_NAME: ${PROJECT_CERT}
    links:
      - web

  web:
    image: meanbee/magento2-nginx:1.9
    hostname: web.${PROJECT_HOSTNAME}
    ports:
      - 80
    volumes_from:
      - magento
    links:
      - fpm

  fpm:
    image: meanbee/magento2-php:7.0-fpm
    hostname: fpm.${PROJECT_HOSTNAME}
    ports:
      - 9000
    volumes_from:
      - magento
    environment:
      ENABLE_SENDMAIL: "true"
      PHP_ENABLE_XDEBUG:
    links:
      - db

  cron:
    image: meanbee/magento2-php:7.0-cli
    hostname: cron.${PROJECT_HOSTNAME}
    command: run-cron
    volumes_from:
      - magento
    environment:
      ENABLE_SENDMAIL: "true"
    links:
      - db

  cli:
    image: meanbee/magento2-php:7.0-cli
    volumes_from:
      - magento
    environment:
      COMPOSER_HOME: /root/.composer
      COMPOSER_ALLOW_SUPERUSER: 1
      M2SETUP_INSTALL_DB: "true"
      M2SETUP_VERSION: 2.2.*
      M2SETUP_USE_SAMPLE_DATA: "true"
      M2SETUP_DB_HOST: db
      M2SETUP_DB_NAME: magento2
      M2SETUP_DB_USER: magento2
      M2SETUP_DB_PASSWORD: magento2
      M2SETUP_BASE_URL: https://${PROJECT_HOSTNAME}/
      M2SETUP_BACKEND_FRONTNAME: admin
      M2SETUP_ADMIN_FIRSTNAME: Admin
      M2SETUP_ADMIN_LASTNAME: User
      M2SETUP_ADMIN_EMAIL: admin@example.com
      M2SETUP_ADMIN_USER: admin
      M2SETUP_ADMIN_PASSWORD: password123
    links:
      - db

  db:
    image: mariadb:10
    ports:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2
      MYSQL_DATABASE: magento2
      TERM: dumb

  magento:
    image: meanbee/magento2-data:2.2-sample
    volumes:
      - .:/extensions/Meanbee_SVGHelper
    environment:
      SYNC_DESTINATION: /extensions/Meanbee_SVGHelper/magento
    privileged: true

volumes:
  dbdata:
    # Database tables

